package com.mini.dataobject;

public class HrDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_info.id
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_info.name
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_info.company
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_info.position
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_info.avatar_url
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_info.id
     *
     * @return the value of hr_info.id
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_info.id
     *
     * @param id the value for hr_info.id
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_info.name
     *
     * @return the value of hr_info.name
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_info.name
     *
     * @param name the value for hr_info.name
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_info.company
     *
     * @return the value of hr_info.company
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_info.company
     *
     * @param company the value for hr_info.company
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_info.position
     *
     * @return the value of hr_info.position
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_info.position
     *
     * @param position the value for hr_info.position
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_info.avatar_url
     *
     * @return the value of hr_info.avatar_url
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_info.avatar_url
     *
     * @param avatarUrl the value for hr_info.avatar_url
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }
}