package com.mini.dao;

import com.mini.dataobject.HrDao;

public interface HrDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_info
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_info
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    int insert(HrDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_info
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    int insertSelective(HrDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_info
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    HrDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_info
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(HrDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_info
     *
     * @mbg.generated Thu May 28 15:43:21 CST 2020
     */
    int updateByPrimaryKey(HrDao record);
}